sudo: false
language: node_js

env:
  matrix: BROWSER=false
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
matrix:
  include:
    - node_js: "4.0"
      env: BROWSER=true
before_install:
  - npm install -g npm@2.6
  - npm install -g karma-cli
before_script:
  - npm install underscore
  - npm install karma-sauce-launcher
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - "[ $BROWSER == false ] || npm run test-browser"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js"
