sudo: false
language: node_js

env:
  matrix: BROWSER=false
  global:
    - secure: lih1JyTVDffYik/Rt4xx6V4ojBVbKWjAGGlB1OdoIXaOCBjMixzmckLWNtLYxZUt8lK5DyDecHfrfmyD4yLhJ7dD5J3JC4bgnR9qj9dQ+HY3oj5N5hOuHpPn39D2a5iI+iAGl3YmncmmD2VNCT5kTZZWy4SkvEhreAQjVBRXSNGm9siczxCbQzZxe92jNQPZ0UvsManMGoMMI4VV8ynL8rLvkJxIPvJODdLkkREzrkZtt1hqATbYWm/49Hh2xAJjBGVuvggwZUBWoo8kUpwVspHOE3nOF45eO7eYrGYX23NUk8mDLjEMtGchccHJ4dqj6hun5RMvMkik3Nc3hamnEozcLoXe+JHyJdEDITBF8MBzeBw3npno/HToPQ2AhhAiE7mUO8hObT9ZjWo7w5SjNx8v5l6i10TB3mxpKVFl68WO6yDKWaokzo/jcYnLpZ4A7FSE0vzcXnfU8MubvHxf8oaQBPxEzZ85sChDZwDlst4W1eThoac9vapZHW8z0xVC85OEBuabw9niFS24y+CHxLuu/MP3XEVhDFeEXmdaA9rytS+6BkALoMb4fmXC3cFUgJr4KSRZcRhSJXghsnD5kZGX1Ag9BK75VW7qKO0nyi/GrEQUOijJmmQEmGRzHFujMVFhGjf6EVWmsoBqKruLcPKLEE+q+SB4XN4RJdt/rgU=
    - secure: SP9TW277yVeVKkGtq8IRwSa+9i/y0X2Ff/EFjsruWlR4p/nQT5z4BQof81hlmHW10x4zV4wC7ODvq722pS9v0jUYA7kYbDUrFb0ucgl5q7erw1ckG/j9XqJ7T8GYX7poJdo84xCUHitrfoRdcjnUKDGFjZVxS1qEz1hC2331UKhLjHX7UxNNia9CNWnSiL639Q0RlxTKLsd+Lg+jLvwzMnT22s272DuQyfWhFpqauOcGV2G5NfQw4RW9hWHCd7sdBcE1BKkzgpAuE5eHUWDTeiR2ACLjbRH0aUOAIaX6wnQXT4B1XvDmsJpXTdySQpcATlfh1KaiKpv9E30FAGONC/B7F1WzZGbisz0v3hy9A062LXo09W91PeRzmGfci+p2vMoh2jQVXph9TFvwk5b6rxBjGv9SuVT7WO/HBTCM4ZotKJbqkpRnpnPKLkHYtoKqdmWfurynUiiySBBFdXJvFvi5dl/O6B6GAtiplHzcw69evPOevIxKNQLcwKhrXKvRnQ5hMH915aUtY0EOyStHX6rvDDE8WpuQryau/sqL0ubgtuDq/t6iVfCmeZOuz3jBGoW8CNcYz4YHjAmwbbmSHgHsumQGgeUZJmq6WLH+UzpaLBludoS3TG/iiKCHP8JnpKKvBQ2NCPKQznHyIvJInlyMOlsCG2zg2kUqca49AKc=

node_js:
  - "0.8"
  - "0.10"
  - "0.12"
matrix:
  include:
    - node_js: "4.0"
      env: BROWSER=true
before_install:
  - npm install -g npm@2.6
  - npm install -g karma-cli
before_script:
  - npm install underscore
  - npm install karma-sauce-launcher
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - "[ $BROWSER == false ] || npm run test-browser"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js"
after_success: npm run coveralls
